var ss = SpreadsheetApp.getActiveSpreadsheet();
var sh = ss.getSheetByName('Cash Flow Valuation');
sh.getRange('B33').setValue("WACC = Cost of Equity * % Equity + Cost of Debt * % Debt * (1 - Tax Rate) + Cost of Preferred Stock * % Preferred Stock");
sh.getRange('D24').setValue(null);
sh.getRange('E23').setFormula('=MEDIAN(E16:E21)');
sh.getRange('E29').setValue(null);
sh.getRange('F23').setFormula('=MEDIAN(F16:F21)');
sh.getRange('F29').setFormula('=F23');
sh.getRange('F31').setValue(null);
sh.getRange('F35').setValue(null);
sh.getRange('F8').setFormula('=Risk_Free_Rate+0.4%');
sh.getRange('G23').setFormula('=MEDIAN(G16:G21)');
sh.getRange('G29').setValue(null);
sh.getRange('H23').setFormula('=MEDIAN(H16:H21)');
sh.getRange('I23').setFormula('=MEDIAN(I16:I21)');
sh.getRange('I29').setValue(null);
sh.getRange('J23').setFormula('=MEDIAN(J16:J21)');
sh.getRange('J29').setFormula('=J23');
sh.getRange('K23').setFormula('=MEDIAN(K16:K21)');
sh.getRange('K29').setFormula('=Tax_Rate');
sh.getRange('L29').setFormula('=D29*(1+(F29/J29)*(1-Tax_Rate)+(H29/J29))');
sh.getRange('L31').setFormula('=Risk_Free_Rate+Equity_Risk_Premium*L29');
sh.getRange('L35').setFormula('=L31*J29+Cost_of_Debt*F29*(1-Tax_Rate)+Cost_of_Preferred*H29');
__LOG__("wrote " + 21 + " cells");