/* Generates shim/20-enums.js and shim/90-spine.js FROM vocab/KEPT.txt, so the
   surface can never silently drift from the agreed scope. Enum namespaces become
   real frozen objects; every other KEPT member is asserted to exist at build time
   and, if unimplemented, installed as a loud thrower. */
import { readFileSync, writeFileSync } from "node:fs";
const KEPT = readFileSync("vocab/KEPT.txt", "utf8");

const classes = {};
let cur = null;
for (const line of KEPT.split("\n")) {
  const h = /^##\s+(\S+)\s+\((\d+)\)/.exec(line);
  if (h) { cur = h[1]; classes[cur] = []; continue; }
  const m = /^\s{2}(\S+)\s*$/.exec(line);
  if (m && cur) classes[cur].push(m[1]);
}
const isEnumName = n => /^[A-Z][A-Z0-9_]*$/.test(n);
const enums = {}, apis = {};
for (const [cls, members] of Object.entries(classes)) {
  if (members.length && members.every(isEnumName)) enums[cls] = members; else apis[cls] = members;
}

/* ---- enums ---- */
let out = `/* GENERATED by gen-surface.mjs from vocab/KEPT.txt — do not edit by hand.
   Each value keeps Apps Script's toString()/name. __excel holds the Excel-side
   mapping where a 1:1 one exists; null means "no unambiguous Excel equivalent",
   and any member whose use requires that mapping throws rather than guessing. */\n`;
out += `function gasEnum(ns, names, excel) {
  var o = {};
  names.forEach(function (n) {
    var v = { name: n, toString: function () { return n; },
              __enum: ns, __excel: (excel && excel[n] !== undefined) ? excel[n] : null };
    Object.freeze(v); o[n] = v;
  });
  return Object.freeze(o);
}\n`;
const EXCEL = {
  BorderStyle: { DOTTED:{style:"Dot",weight:"Thin"}, DASHED:{style:"Dash",weight:"Thin"},
    SOLID:{style:"Continuous",weight:"Thin"}, SOLID_MEDIUM:{style:"Continuous",weight:"Medium"},
    SOLID_THICK:{style:"Continuous",weight:"Thick"}, /* OOXML has ONE double border style and no weight variants, so mog accepts Double only
     with Thin -- Double+Thick was rejected outright and setBorder(BorderStyle.DOUBLE)
     threw for every caller. */
    DOUBLE:{style:"Double",weight:"Thin"} },
  Dimension: { COLUMNS:"Columns", ROWS:"Rows" },
  Direction: { UP:"Up", DOWN:"Down", PREVIOUS:"Left", NEXT:"Right" },
  SortOrder: { ASCENDING:true, DESCENDING:false },
  SheetType: { GRID:"Worksheet", OBJECT:"Chartsheet", DATASOURCE:null }
};
const enumNames = Object.keys(enums).sort();
for (const e of enumNames) {
  out += `var ${e} = gasEnum(${JSON.stringify(e)}, ${JSON.stringify(enums[e])}` +
         (EXCEL[e] ? `, ${JSON.stringify(EXCEL[e])}` : ``) + `);\n`;
}
out += `var GAS_ENUMS = { ${enumNames.map(e => `${e}: ${e}`).join(", ")} };\n`;
writeFileSync("shim/20-enums.js", out);

/* ---- spine: every non-enum KEPT member must exist ---- */
let spine = `/* GENERATED by gen-surface.mjs — the loud-failure spine.
   Every KEPT member that has no implementation becomes a thrower, so an unbuilt
   member fails visibly instead of silently returning undefined (a false green). */\n`;
spine += `var GAS_SURFACE = ${JSON.stringify(apis, null, 1)};\n`;
spine += `var GAS_COVERAGE;
(function () {
  var hosts = { SpreadsheetApp: typeof SpreadsheetApp !== "undefined" && SpreadsheetApp,
                Range: typeof Range !== "undefined" && Range.prototype,
                Sheet: typeof Sheet !== "undefined" && Sheet.prototype,
                Spreadsheet: typeof Spreadsheet !== "undefined" && Spreadsheet.prototype,
                RangeList: typeof RangeList !== "undefined" && RangeList.prototype,
                TextFinder: typeof TextFinder !== "undefined" && TextFinder.prototype,
                DataValidation: typeof DataValidation !== "undefined" && DataValidation.prototype,
                DataValidationBuilder: typeof DataValidationBuilder !== "undefined" && DataValidationBuilder.prototype,
                ConditionalFormatRule: typeof ConditionalFormatRule !== "undefined" && ConditionalFormatRule.prototype,
                ConditionalFormatRuleBuilder: typeof ConditionalFormatRuleBuilder !== "undefined" && ConditionalFormatRuleBuilder.prototype,
                NamedRange: typeof NamedRange !== "undefined" && NamedRange.prototype,
                TextStyle: typeof TextStyle !== "undefined" && TextStyle.prototype,
                TextStyleBuilder: typeof TextStyleBuilder !== "undefined" && TextStyleBuilder.prototype,
                RgbColor: typeof RgbColor !== "undefined" && RgbColor.prototype,
                Color: typeof Color !== "undefined" && Color.prototype,
                ColorBuilder: typeof ColorBuilder !== "undefined" && ColorBuilder.prototype,
                ThemeColor: typeof ThemeColor !== "undefined" && ThemeColor.prototype,
                BooleanCondition: typeof BooleanCondition !== "undefined" && BooleanCondition.prototype,
                GradientCondition: typeof GradientCondition !== "undefined" && GradientCondition.prototype };
  GAS_COVERAGE = { implemented: 0, missing: 0, outOfScope: 0, byClass: {} };
  Object.keys(GAS_SURFACE).forEach(function (cls) {
    var proto = hosts[cls];
    var impl = 0, miss = 0, oos = 0;
    GAS_SURFACE[cls].forEach(function (m) {
      if (!proto) { miss++; return; }
      var f = proto[m];
      if (typeof f === "function" && !f.__unimplemented) {
        if (f.__outOfScope) { oos++; return; }     // deliberately unsupported, counted apart
        impl++; return;
      }
      if (typeof f !== "function") proto[m] = GAS.notImplemented(cls + "." + m);
      miss++;
    });
    GAS_COVERAGE.byClass[cls] = { implemented: impl, missing: miss, outOfScope: oos };
    GAS_COVERAGE.implemented += impl; GAS_COVERAGE.missing += miss; GAS_COVERAGE.outOfScope += oos;
    /* Apps Script hands back OPAQUE host objects: String(v) is the class name and the
       constructor is plain Object, not the class. Verified against real Apps Script for
       every class in the surface. Done here so a new class can never forget it. */
    if (proto && !Object.prototype.hasOwnProperty.call(proto, "__opaque")) {
      proto.toString = (function (n) { return function () { return n; }; })(cls);
      proto.constructor = Object;
      Object.defineProperty(proto, "__opaque", { value: true, enumerable: false });
    }
    /* Anything NOT in the surface reaches the catch-all instead of dying as
       "undefined is not a function". Installed last so every real member shadows it. */
    if (proto) {
      var base = Object.getPrototypeOf(proto);
      if (!base || !base.__outOfSurfaceBase) {
        var fallback = GAS.outsideSurface(cls);
        try { Object.setPrototypeOf(proto, fallback); } catch (e) { /* frozen host: skip */ }
      }
    }
  });
})();\n`;
writeFileSync("shim/90-spine.js", spine);
const nEnum = enumNames.reduce((a, e) => a + enums[e].length, 0);
const nApi = Object.values(apis).reduce((a, m) => a + m.length, 0);
console.log(`generated: ${enumNames.length} enum namespaces (${nEnum} values), ${Object.keys(apis).length} API classes (${nApi} members)`);
