/* GENERATED by gen-surface.mjs from vocab/KEPT.txt — do not edit by hand.
   Each value keeps Apps Script's toString()/name. __excel holds the Excel-side
   mapping where a 1:1 one exists; null means "no unambiguous Excel equivalent",
   and any member whose use requires that mapping throws rather than guessing. */
function gasEnum(ns, names, excel) {
  var o = {};
  names.forEach(function (n) {
    var v = { name: n, toString: function () { return n; },
              __enum: ns, __excel: (excel && excel[n] !== undefined) ? excel[n] : null };
    Object.freeze(v); o[n] = v;
  });
  return Object.freeze(o);
}
var AutoFillSeries = gasEnum("AutoFillSeries", ["ALTERNATE_SERIES","DEFAULT_SERIES"]);
var BooleanCriteria = gasEnum("BooleanCriteria", ["CELL_EMPTY","CELL_NOT_EMPTY","CUSTOM_FORMULA","DATE_AFTER","DATE_AFTER_RELATIVE","DATE_BEFORE","DATE_BEFORE_RELATIVE","DATE_EQUAL_TO","DATE_EQUAL_TO_RELATIVE","DATE_NOT_EQUAL_TO","NUMBER_BETWEEN","NUMBER_EQUAL_TO","NUMBER_GREATER_THAN","NUMBER_GREATER_THAN_OR_EQUAL_TO","NUMBER_LESS_THAN","NUMBER_LESS_THAN_OR_EQUAL_TO","NUMBER_NOT_BETWEEN","NUMBER_NOT_EQUAL_TO","TEXT_CONTAINS","TEXT_DOES_NOT_CONTAIN","TEXT_ENDS_WITH","TEXT_EQUAL_TO","TEXT_NOT_EQUAL_TO","TEXT_STARTS_WITH"]);
var BorderStyle = gasEnum("BorderStyle", ["DASHED","DOTTED","DOUBLE","SOLID","SOLID_MEDIUM","SOLID_THICK"], {"DOTTED":{"style":"Dot","weight":"Thin"},"DASHED":{"style":"Dash","weight":"Thin"},"SOLID":{"style":"Continuous","weight":"Thin"},"SOLID_MEDIUM":{"style":"Continuous","weight":"Medium"},"SOLID_THICK":{"style":"Continuous","weight":"Thick"},"DOUBLE":{"style":"Double","weight":"Thin"}});
var ColorType = gasEnum("ColorType", ["RGB","THEME","UNSUPPORTED"]);
var CopyPasteType = gasEnum("CopyPasteType", ["PASTE_CONDITIONAL_FORMATTING","PASTE_DATA_VALIDATION","PASTE_FORMAT","PASTE_FORMULA","PASTE_NORMAL","PASTE_NO_BORDERS","PASTE_VALUES"]);
var DataValidationCriteria = gasEnum("DataValidationCriteria", ["CUSTOM_FORMULA","DATE_AFTER","DATE_AFTER_RELATIVE","DATE_BEFORE","DATE_BEFORE_RELATIVE","DATE_BETWEEN","DATE_EQUAL_TO","DATE_EQUAL_TO_RELATIVE","DATE_IS_VALID_DATE","DATE_NOT_BETWEEN","DATE_ON_OR_AFTER","DATE_ON_OR_BEFORE","NUMBER_BETWEEN","NUMBER_EQUAL_TO","NUMBER_GREATER_THAN","NUMBER_GREATER_THAN_OR_EQUAL_TO","NUMBER_LESS_THAN","NUMBER_LESS_THAN_OR_EQUAL_TO","NUMBER_NOT_BETWEEN","NUMBER_NOT_EQUAL_TO","TEXT_CONTAINS","TEXT_DOES_NOT_CONTAIN","TEXT_EQUAL_TO","TEXT_IS_VALID_EMAIL","TEXT_IS_VALID_URL","VALUE_IN_LIST","VALUE_IN_RANGE"]);
var Dimension = gasEnum("Dimension", ["COLUMNS","ROWS"], {"COLUMNS":"Columns","ROWS":"Rows"});
var Direction = gasEnum("Direction", ["DOWN","NEXT","PREVIOUS","UP"], {"UP":"Up","DOWN":"Down","PREVIOUS":"Left","NEXT":"Right"});
var InterpolationType = gasEnum("InterpolationType", ["MAX","MIN","NUMBER","PERCENT","PERCENTILE"]);
var RelativeDate = gasEnum("RelativeDate", ["PAST_MONTH","PAST_WEEK","PAST_YEAR","TODAY","TOMORROW","YESTERDAY"]);
var SheetType = gasEnum("SheetType", ["DATASOURCE","GRID","OBJECT"], {"GRID":"Worksheet","OBJECT":"Chartsheet","DATASOURCE":null});
var SortOrder = gasEnum("SortOrder", ["ASCENDING","DESCENDING"], {"ASCENDING":true,"DESCENDING":false});
var ThemeColorType = gasEnum("ThemeColorType", ["ACCENT1","ACCENT2","ACCENT3","ACCENT4","ACCENT5","ACCENT6","BACKGROUND","HYPERLINK","TEXT","UNSUPPORTED"]);
var GAS_ENUMS = { AutoFillSeries: AutoFillSeries, BooleanCriteria: BooleanCriteria, BorderStyle: BorderStyle, ColorType: ColorType, CopyPasteType: CopyPasteType, DataValidationCriteria: DataValidationCriteria, Dimension: Dimension, Direction: Direction, InterpolationType: InterpolationType, RelativeDate: RelativeDate, SheetType: SheetType, SortOrder: SortOrder, ThemeColorType: ThemeColorType };
